---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# ATRA Climate Change Explorer

You can access the app [HERE](https://mirzaceng.shinyapps.io/ATRAClimateChangeExplorer/).

The ATRA Climate Explorer is an interactive tool designed to assess the potential impacts of climate change on amphibian and reptile species (herpetofauna) in Bosnia and Herzegovina by leveraging open GBIF data. This Shiny app is developed and hosted by the Herpetological Association of Bosnia and Herzegovina ([BHHU - ATRA](https://www.bhhuatra.com/)). We designed to be easily adaptable for different regions and sets of species. Users can clone the GitHub repository, modify the configuration and data files, and deploy their own version of the app. 

## How to use the app?

See detailed instructions in the app's About page.

## How to build my own Climate Change Explorer app?

See detailed instructions in the app's How to Build Your Own? page.

## Project Structure

- `app.R`: Main Shiny app file
- `R/functions.R`: File containing helper functions
- `download_data.R`: helper script to download data when adapting the app to custom needs
- `data/`: Directory for storing data files

## License

This project is licensed under the MIT License.